services:
  # Backend API service
  - type: web
    name: ai-summarizer-backend
    env: python
    plan: free
    buildCommand: apt-get update && apt-get install -y tesseract-ocr && pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
